import { PrismaClient } from '@prisma/client';
import * as bcrypt from 'bcrypt';

const prisma = new PrismaClient();

/** 외부 샘플 (네트워크 필요) */
const demoVideoUrl =
  'https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4';

/**
 * 프론트 정적 파일 URL (DB에 문자열만 저장하는 예시).
 * Vite는 `frontend/public`을 루트로 제공하므로 브라우저에서 `/media/demo-drone-map.mp4` 로 재생됩니다.
 * `적군-ALPHA` 한 건만 로컬 파일로 연결해 지도에서 동작을 확인합니다.
 */
const localMapDroneVideoUrl = '/media/demo-drone-map.mp4';

async function main() {
  await prisma.unit.deleteMany();
  await prisma.infiltrationPoint.deleteMany();

  const demoEmails = ['demo@hanhwa.local', 'viewer@hanhwa.local'] as const;
  await prisma.user.deleteMany({ where: { email: { in: [...demoEmails] } } });

  const demoHash = await bcrypt.hash('Demo1234!', 10);
  await prisma.user.createMany({
    data: [
      { email: demoEmails[0], passwordHash: demoHash, name: '모의 지휘관' },
      { email: demoEmails[1], passwordHash: demoHash, name: '모의 관제' },
    ],
  });

  await prisma.unit.createMany({
    data: [
      {
        name: '1기갑대대 본부',
        level: '대대',
        branch: '기갑',
        lat: 37.5665,
        lng: 126.978,
        personnel: 430,
        equipment: 'K2 18대, K21 14대',
        readiness: '최고',
        mission: '수도권 서북부 방어',
        symbolType: 'ARMOR',
        locationStatus: 'CURRENT',
        strengthModifier: 'REINFORCED',
        situationVideoUrl: localMapDroneVideoUrl,
      },
      {
        name: '23중대',
        level: '중대',
        branch: '기계화보병',
        lat: 37.4563,
        lng: 126.7052,
        personnel: 125,
        equipment: 'K808 9대, 정찰드론 3기',
        readiness: '경계',
        mission: '항만 및 물류 거점 방호',
        symbolType: 'MECHANIZED_INFANTRY',
        locationStatus: 'CURRENT',
        strengthModifier: 'NONE',
        situationVideoUrl: demoVideoUrl,
      },
      {
        name: '11소대',
        level: '소대',
        branch: '정찰',
        lat: 35.1796,
        lng: 129.0756,
        personnel: 34,
        equipment: '경정찰차 4대, 소형 UAV 2기',
        readiness: '양호',
        mission: '남동권 해안 감시',
        symbolType: 'RECON',
        locationStatus: 'CURRENT',
        strengthModifier: 'NONE',
        situationVideoUrl: demoVideoUrl,
      },
      {
        name: '7포병대대',
        level: '대대',
        branch: '포병',
        lat: 36.3504,
        lng: 127.3845,
        personnel: 390,
        equipment: 'K9A1 12문, 대포병 레이더 2기',
        readiness: '경계',
        mission: '중부권 화력 지원',
        symbolType: 'ARTILLERY',
        locationStatus: 'CURRENT',
        strengthModifier: 'NONE',
        situationVideoUrl: localMapDroneVideoUrl,
      },
      {
        name: '5보병중대',
        level: '중대',
        branch: '보병',
        lat: 37.8859,
        lng: 127.73,
        personnel: 118,
        equipment: '소총, 유탄, 중기관총',
        readiness: '경계',
        mission: '동부 전선 전술거점',
        symbolType: 'INFANTRY',
        locationStatus: 'CURRENT',
        strengthModifier: 'REDUCED',
        situationVideoUrl: demoVideoUrl,
      },
      {
        name: '3공병소대',
        level: '소대',
        branch: '공병',
        lat: 36.019,
        lng: 129.343,
        personnel: 28,
        equipment: '장애물 개척, 도로 복구 장비',
        readiness: '양호',
        mission: '후방 도로 확보',
        symbolType: 'ENGINEER',
        locationStatus: 'PLANNED',
        strengthModifier: 'NONE',
        situationVideoUrl: demoVideoUrl,
      },
      {
        name: '8방공포대대',
        level: '대대',
        branch: '방공',
        lat: 35.8714,
        lng: 128.6014,
        personnel: 210,
        equipment: '천궁, 비호복합',
        readiness: '최고',
        mission: '주요 거점 대공 방어',
        symbolType: 'ADA',
        locationStatus: 'CURRENT',
        strengthModifier: 'NONE',
        situationVideoUrl: localMapDroneVideoUrl,
      },
      {
        name: '예비 집결 A',
        level: '대대',
        branch: '보병',
        lat: 36.78,
        lng: 126.45,
        personnel: 0,
        equipment: '(예정)',
        readiness: '양호',
        mission: '2차 방어선 예비 배치',
        symbolType: 'INFANTRY',
        locationStatus: 'PLANNED',
        strengthModifier: 'NONE',
        situationVideoUrl: demoVideoUrl,
      },
      {
        name: '12기갑중대',
        level: '중대',
        branch: '기갑',
        lat: 34.8118,
        lng: 126.3922,
        personnel: 95,
        equipment: 'K2 6대',
        readiness: '경계',
        mission: '남서해안 기동 예비대',
        symbolType: 'ARMOR',
        locationStatus: 'CURRENT',
        strengthModifier: 'NONE',
        situationVideoUrl: localMapDroneVideoUrl,
      },
      {
        name: '2포병중대',
        level: '중대',
        branch: '포병',
        lat: 38.207,
        lng: 128.591,
        personnel: 102,
        equipment: 'K55A1 6문',
        readiness: '경계',
        mission: '동해안 간접사격 지원',
        symbolType: 'ARTILLERY',
        locationStatus: 'PLANNED',
        strengthModifier: 'REINFORCED',
        situationVideoUrl: demoVideoUrl,
      },
      {
        name: '정찰대 4',
        level: '소대',
        branch: '정찰',
        lat: 33.4996,
        lng: 126.5312,
        personnel: 22,
        equipment: '소총, 야투시경',
        readiness: '양호',
        mission: '제주 방향 해안 정찰',
        symbolType: 'RECON',
        locationStatus: 'CURRENT',
        strengthModifier: 'NONE',
        situationVideoUrl: localMapDroneVideoUrl,
      },
      {
        name: '6기계화대대',
        level: '대대',
        branch: '기계화보병',
        lat: 37.2636,
        lng: 127.0286,
        personnel: 340,
        equipment: 'K200 시리즈, K21',
        readiness: '최고',
        mission: '수도권 남동 기동',
        symbolType: 'MECHANIZED_INFANTRY',
        locationStatus: 'CURRENT',
        strengthModifier: 'NONE',
        situationVideoUrl: localMapDroneVideoUrl,
      },
      {
        name: '4기갑소대 (전방)',
        level: '소대',
        branch: '기갑',
        lat: 37.8813,
        lng: 127.7297,
        personnel: 42,
        equipment: 'K2 4대',
        readiness: '경계',
        mission: '동부 전술거점 직접 경계',
        symbolType: 'ARMOR',
        locationStatus: 'CURRENT',
        strengthModifier: 'NONE',
        situationVideoUrl: localMapDroneVideoUrl,
      },
      {
        name: '9자주포포대',
        level: '중대',
        branch: '포병',
        lat: 35.1595,
        lng: 126.8526,
        personnel: 88,
        equipment: 'K9A1 6문',
        readiness: '최고',
        mission: '남서권 화력 예비',
        symbolType: 'ARTILLERY',
        locationStatus: 'CURRENT',
        strengthModifier: 'REINFORCED',
        situationVideoUrl: demoVideoUrl,
      },
    ],
  });

  await prisma.infiltrationPoint.createMany({
    data: [
      {
        codename: '적군-ALPHA',
        lat: 38.128,
        lng: 127.274,
        threatLevel: '높음',
        estimatedCount: 18,
        observedAt: new Date('2026-03-19T07:40:00'),
        riskRadiusMeter: 4200,
        droneVideoUrl: localMapDroneVideoUrl,
        enemySymbol: 'ENEMY_UNIT',
        enemyBranch: '기갑 (전차 편대 추정)',
      },
      {
        codename: '적군-BRAVO',
        lat: 37.902,
        lng: 128.316,
        threatLevel: '중간',
        estimatedCount: 9,
        observedAt: new Date('2026-03-19T08:15:00'),
        riskRadiusMeter: 2500,
        droneVideoUrl: demoVideoUrl,
        enemySymbol: 'ENEMY_UNIT',
        enemyBranch: '기갑·포병 혼성 (수송·지원)',
      },
      {
        codename: '적군-CHARLIE',
        lat: 35.953,
        lng: 129.381,
        threatLevel: '낮음',
        estimatedCount: 5,
        observedAt: new Date('2026-03-19T08:43:00'),
        riskRadiusMeter: 1600,
        droneVideoUrl: demoVideoUrl,
        enemySymbol: 'ENEMY_STRONGPOINT',
        enemyBranch: '자주포·포병 진지',
      },
      {
        codename: '적군-DELTA',
        lat: 37.4111,
        lng: 129.1683,
        threatLevel: '중간',
        estimatedCount: 12,
        observedAt: new Date('2026-03-20T05:10:00'),
        riskRadiusMeter: 3100,
        droneVideoUrl: demoVideoUrl,
        enemySymbol: 'ENEMY_UNIT',
        enemyBranch: '포병 (곡사·로켓 추정)',
      },
      {
        codename: '적군-ECHO',
        lat: 36.1198,
        lng: 128.3446,
        threatLevel: '높음',
        estimatedCount: 22,
        observedAt: new Date('2026-03-20T06:00:00'),
        riskRadiusMeter: 3800,
        droneVideoUrl: demoVideoUrl,
        enemySymbol: 'ENEMY_STRONGPOINT',
        enemyBranch: '다연장·화력 진지',
      },
      {
        codename: '적군-FOXTROT',
        lat: 34.76,
        lng: 127.66,
        threatLevel: '낮음',
        estimatedCount: 4,
        observedAt: new Date('2026-03-20T07:22:00'),
        riskRadiusMeter: 1200,
        droneVideoUrl: demoVideoUrl,
        enemySymbol: 'ENEMY_UNIT',
        enemyBranch: '기갑 정찰 (장갑차량)',
      },
      {
        codename: '적군-GOLF',
        lat: 35.5384,
        lng: 129.3113,
        threatLevel: '중간',
        estimatedCount: 15,
        observedAt: new Date('2026-03-20T08:05:00'),
        riskRadiusMeter: 2900,
        droneVideoUrl: demoVideoUrl,
        enemySymbol: 'ENEMY_UNIT',
        enemyBranch: '기갑·기계화 혼성',
      },
      {
        codename: '적군-HOTEL',
        lat: 38.501,
        lng: 127.303,
        threatLevel: '낮음',
        estimatedCount: 6,
        observedAt: new Date('2026-03-20T09:30:00'),
        riskRadiusMeter: 2000,
        droneVideoUrl: demoVideoUrl,
        enemySymbol: 'ENEMY_STRONGPOINT',
        enemyBranch: '포병 관측·교정 거점',
      },
      {
        codename: '적군-INDIA',
        lat: 37.2752,
        lng: 126.7028,
        threatLevel: '중간',
        estimatedCount: 11,
        observedAt: new Date('2026-03-21T04:20:00'),
        riskRadiusMeter: 2200,
        droneVideoUrl: localMapDroneVideoUrl,
        enemySymbol: 'ENEMY_UNIT',
        enemyBranch: '기갑 (전술 기동 추정)',
      },
      {
        codename: '적군-JULIET',
        lat: 36.4914,
        lng: 127.2568,
        threatLevel: '높음',
        estimatedCount: 28,
        observedAt: new Date('2026-03-21T05:45:00'),
        riskRadiusMeter: 4500,
        droneVideoUrl: demoVideoUrl,
        enemySymbol: 'ENEMY_STRONGPOINT',
        enemyBranch: '포병·다연장 혼합 진지',
      },
    ],
  });

  console.log(
    'Seed 완료: 모의 로그인 계정 (기존 동일 이메일은 삭제 후 재생성)',
    demoEmails.join(', '),
    '/ 비밀번호: Demo1234!',
  );
  console.log(
    '  Unit',
    await prisma.unit.count(),
    '개, InfiltrationPoint',
    await prisma.infiltrationPoint.count(),
    '개',
  );
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
