-- AlterTable
ALTER TABLE `infiltrationpoint` ADD COLUMN `enemyBranch` VARCHAR(191) NOT NULL DEFAULT '미상',
    ADD COLUMN `enemySymbol` ENUM('ENEMY_UNIT', 'ENEMY_STRONGPOINT') NOT NULL DEFAULT 'ENEMY_UNIT';

-- AlterTable
ALTER TABLE `unit` ADD COLUMN `locationStatus` ENUM('CURRENT', 'PLANNED') NOT NULL DEFAULT 'CURRENT',
    ADD COLUMN `strengthModifier` ENUM('NONE', 'REINFORCED', 'REDUCED') NOT NULL DEFAULT 'NONE',
    ADD COLUMN `symbolType` ENUM('INFANTRY', 'ARTILLERY', 'ARMOR', 'MECHANIZED_INFANTRY', 'RECON', 'ENGINEER', 'ADA') NOT NULL DEFAULT 'INFANTRY';
